### ISSUE TITLE
no sound in windows dual boot

### ISSUE THREAD

**Issue by Trilis29** [dawidmalina/xiaomi-mi-pro-15.6-enhanced#1]
Hi, 

There is sometimes no sound in windows on dual boot. Seems it's kinda related to AudioDxe.efi, if I delete it, and reinstall drivers sound works again. Don't know where is the exact problem with this driver.

**Comment by dawidmalina** [comment]
Thanks for sharing this.

**Comment by dawidmalina** [comment]
> AudioDxe-64.efi HDA Driver to play start up chime / start up sound at boot time.

I think that we can (at least for now) just remove it.

**Comment by dawidmalina** [comment]
I am not interested in this topic.
