### ISSUE TITLE
intel wifi and bluetooth?

### ISSUE THREAD

**Issue by Trilis29** [dawidmalina/xiaomi-mi-pro-15.6-enhanced#2]
Have you made any of this to work?

**Comment by dawidmalina** [comment]
No. Still have issue with this.

**Comment by nekiro** [comment]
It's most likely impossible to make this work (with stock wifi/bluetooth card). You have to buy macOS compatible wireless card.
More info: https://osxlatitude.com/forums/topic/11138-inventory-of-supportedunsupported-wireless-cards-2-sierra-catalina/

**Comment by dawidmalina** [comment]
I am not interested in this topic.
